{
 "title": "MAP@CADDY",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "MAP@CADDY",
   "type": "geomap",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT lat,lon\nFROM caddy_fct\nINNER JOIN ip_data\nON query = ip\nWHERE $__timeFilter(time_reported)"
    }
   ]
  },
  {
   "title": "Domains accessing my websites",
   "type": "piechart",
   "description": "This is a bunch of hijacked server/ honeypots :p",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \ndomain,\ncount(1)\nFROM caddy_fct \nLEFT JOIN ip2domain \nON caddy_fct.ip = ip2domain.ip\nWHERE domain != 'None'\nAND $__timeFilter(caddy_fct.time_reported) \nGROUP BY 1\nORDER BY 2 DESC \nLIMIT 10"
    }
   ]
  },
  {
   "title": "Common IP's",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    CONCAT(host, uri) as uri,\n    COUNT(*) AS count_\nFROM caddy_fct\nWHERE host NOT IN ('grafana.notedwin.com','portainer.notedwin.com')\nAND $__timeFilter(time_reported)\nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Common IP's",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "rawSql": "SELECT ip,\n    COUNT(*) AS count_\nFROM caddy_fct\nWHERE ip != '73.209.167.249'\n    AND $__timeFilter(time_reported)\nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Unique IP's",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT $__timeGroup(time_reported, '1d'),\n    COUNT(DISTINCT ip) AS ip\nFROM caddy_fct\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Weekly rolling average resting hr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as avg_\nFROM (\n  SELECT \n    \"startDate\"::DATE as time,\n    AVG(value::FLOAT) as value\n  FROM \"RestingHeartRate\" \n  GROUP BY 1\n) as subquery\nORDER BY 1;\n\n\n\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datastr::json->>'title' as project,\n  SUM(duration) as seconds_worked_on\nFROM eventmodel \nWHERE bucket_id IN (1,5,6,7,9,10,15,16)\nAND datastr::json->>'app' = 'Code'\nAND timestamp > $__timeFrom() \nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 5"
    }
   ]
  },
  {
   "title": "Standing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE, '1w'),\nSUM(value::FLOAT) as week_avg\nFROM \"AppleStandTime\" \nGROUP BY 1"
    },
    {
     "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE + interval '1 month', '30d'),\nSUM(value::FLOAT)/30*6 as month_avg\nFROM \"AppleStandTime\" \nGROUP BY 1"
    },
    {
     "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE + interval '4 months', '120d'),\nSUM(value::FLOAT)/120*6 as four_month_avg\nFROM \"AppleStandTime\" \nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Exercise Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE, '1w'),\nSUM(value::FLOAT) as week_avg\nFROM \"AppleExerciseTime\" \nGROUP BY 1"
    },
    {
     "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as rolling_weekly_avg\nFROM (\n  SELECT \n    \"startDate\"::DATE as time,\n    SUM(value::FLOAT) as value\n  FROM \"AppleExerciseTime\" \n  GROUP BY 1\n) as subquery\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Rolling Average MS on vscode",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as avg_screen_time\nFROM (\n  SELECT\n    zstartdate::date as time,\n    SUM(EXTRACT(EPOCH FROM (zenddate - zstartdate))) as value\n  FROM apple_screentime \n  WHERE zvaluestring = 'com.microsoft.VSCode'\n  GROUP BY 1\n) as subquery\nORDER BY 1;"
    },
    {
     "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as avg_aw_time\nFROM (\n  SELECT\n    timestamp::date as time,\n    SUM(duration) as value\n  FROM eventmodel \n  WHERE bucket_id IN (1,5,6,7,9,10,15,16)\n  AND datastr::json->>'app' = 'Code'\n  GROUP BY 1\n) as subquery\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Step Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE, '1w'),\nSUM(value::INT) as week_avg\nFROM \"StepCount\" \nGROUP BY 1"
    },
    {
     "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as rolling_weekly_avg\nFROM (\n  SELECT \n    \"startDate\"::DATE as time,\n    SUM(value::FLOAT) as value\n  FROM \"StepCount\" \n  GROUP BY 1\n) as subquery\nORDER BY 1;\n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT \nDATE_PART('year', timestamp::date) as year,\nSUM(duration)/3600 as hours_coding\n  FROM eventmodel \n  WHERE bucket_id IN (1,5,6,7,9,10,15,16)\n  AND datastr::json->>'app' = 'Code'\n  GROUP BY 1"
    }
   ]
  },
  {
   "title": "Step Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE, '1w'),\nSUM(value::FLOAT) as week_avg\nFROM \"DistanceWalkingRunning\" \nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(avg_over_time(node_nat_traffic{src=~\"192.168.0.115|192.168.0.122\", dest=~\".+\"}[$__interval])) < sum(avg_over_time(node_nat_traffic{src=~\"192.168.0.115|192.168.0.122\", dest=~\".+\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}