{
 "title": "Personal",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "coding",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT\n  datastr::json->>'title' as project,\n  SUM(duration) as seconds_worked_on\nFROM eventmodel \nWHERE bucket_id IN (1,5,6,7,9,10,15,16)\nAND datastr::json->>'app' = 'Code'\nAND timestamp > $__timeFrom() \nGROUP BY 1\nORDER BY 2 DESC\nLIMIT 5"
      }
     ]
    },
    {
     "title": "Time coding by year",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 12, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT \nDATE_PART('year', timestamp::date) as year,\nSUM(duration)/3600 as hours_coding\n  FROM eventmodel \n  WHERE bucket_id IN (1,5,6,7,9,10,15,16)\n  AND datastr::json->>'app' = 'Code'\n  GROUP BY 1"
      }
     ]
    },
    {
     "title": "Time on computer (not right)",
     "type": "table",
     "gridPos": { "h": 8, "w": 5, "x": 17, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT \nDATE_PART('year', timestamp::date) as year,\nSUM(duration)/3600 as hours\nFROM eventmodel \nGROUP BY 1"
      }
     ]
    },
    {
     "title": "Rolling Average MS on vscode",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as avg_screen_time\nFROM (\n  SELECT\n    zstartdate::date as time,\n    SUM(EXTRACT(EPOCH FROM (zenddate - zstartdate))) as value\n  FROM apple_screentime \n  WHERE zvaluestring = 'com.microsoft.VSCode'\n  GROUP BY 1\n) as subquery\nORDER BY 1;"
      },
      {
       "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as avg_aw_time\nFROM (\n  SELECT\n    timestamp::date as time,\n    SUM(duration) as value\n  FROM eventmodel \n  WHERE bucket_id IN (1,5,6,7,9,10,15,16)\n  AND datastr::json->>'app' = 'Code'\n  GROUP BY 1\n) as subquery\nORDER BY 1;"
      }
     ]
    }
   ]
  },
  {
   "title": "Health Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Standing Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE, '1w'),\nSUM(value::FLOAT) as week_avg\nFROM \"AppleStandTime\" \nGROUP BY 1"
      },
      {
       "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE + interval '1 month', '30d'),\nSUM(value::FLOAT)/30*6 as month_avg\nFROM \"AppleStandTime\" \nGROUP BY 1"
      },
      {
       "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE + interval '4 months', '120d'),\nSUM(value::FLOAT)/120*6 as four_month_avg\nFROM \"AppleStandTime\" \nGROUP BY 1"
      }
     ]
    },
    {
     "title": "Weekly rolling average resting hr",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as avg_\nFROM (\n  SELECT \n    \"startDate\"::DATE as time,\n    AVG(value::FLOAT) as value\n  FROM \"RestingHeartRate\" \n  GROUP BY 1\n) as subquery\nORDER BY 1;\n\n\n\n"
      }
     ]
    },
    {
     "title": "Exercise Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE, '1w'),\nSUM(value::FLOAT) as week_avg\nFROM \"AppleExerciseTime\" \nGROUP BY 1"
      },
      {
       "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as rolling_weekly_avg\nFROM (\n  SELECT \n    \"startDate\"::DATE as time,\n    SUM(value::FLOAT) as value\n  FROM \"AppleExerciseTime\" \n  GROUP BY 1\n) as subquery\nORDER BY 1;\n"
      }
     ]
    },
    {
     "title": "Step Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE, '1w'),\nSUM(value::INT) as week_avg\nFROM \"StepCount\" \nGROUP BY 1"
      },
      {
       "rawSql": "SELECT \n  time,\n  AVG(value::FLOAT) OVER (ORDER BY time ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) as rolling_weekly_avg\nFROM (\n  SELECT \n    \"startDate\"::DATE as time,\n    SUM(value::FLOAT) as value\n  FROM \"StepCount\" \n  GROUP BY 1\n) as subquery\nORDER BY 1;\n"
      }
     ]
    },
    {
     "title": "Step Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 26 },
     "targets": [
      {
       "rawSql": "SELECT \n$__timeGroup(\"startDate\"::DATE, '1w'),\nSUM(value::FLOAT) as week_avg\nFROM \"DistanceWalkingRunning\" \nGROUP BY 1"
      }
     ]
    }
   ]
  },
  { "title": "Cloudflare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Cloudflare",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n$__timeGroup(date::date, '1d'),\nSUM(requests) as requests\nFROM cloudflare_analytics\nWHERE $__timeFilter(date) \nGROUP BY 1"
    },
    {
     "rawSql": "SELECT \n$__timeGroup(date::date, '1d'),\nSUM(Uniques) as unique_visitors\nFROM cloudflare_analytics\nWHERE $__timeFilter(date) \nGROUP BY 1"
    }
   ]
  },
  {
   "title": "cached_bytes_percentage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nSUM(CachedBytes)/SUM(Bytes) as cached_percentage\nFROM cloudflare_analytics\nWHERE $__timeFilter(date) "
    }
   ]
  }
 ]
}