---
- name: Copy resume.pdf
  copy:
    src: ./configs/resume.pdf
    dest: /home/notedwin2/docker/caddy/resume.pdf
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Copy Caddyfile
  copy:
    src: ./configs/caddyfile
    dest: /home/notedwin2/docker/caddy/Caddyfile
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Copy dockerfile
  copy:
    src: ./configs/dockerfile
    dest: /home/notedwin2/docker/caddy/Dockerfile
    owner: notedwin2
    group: notedwin2
    mode: 0644
    force: yes

- name: Build Docker image
  docker_image:
    name: caddy-ts
    source: build
    build:
      path: /home/notedwin2/docker/caddy/

# become_user: notedwin
# command: docker build -t caddy-yuh /home/notedwin

- name: Run Caddy
  docker_container:
    restart: yes
    user: root
    name: caddy
    image: caddy-ts
    state: started
    restart_policy: always
    network_mode: net
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - /home/notedwin2/docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /home/notedwin2/docker/caddy:/data
      - /home/notedwin2/docker/caddy:/config
      - /var/log/caddy/:/var/log/caddy/
      - /home/notedwin2/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      - /home/notedwin2/docker/caddy/resume.pdf:/resume/resume.pdf
      - /home/notedwin2/til/:/til/
