---
- name: Copy grafana folder
  copy:
    src: ./config/grafana/
    dest: /home/notedwin2/docker/grafana/
    owner: notedwin2
    group: notedwin2
    mode: 0644
    force: yes

- name: Run Grafana container
  docker_container:
    name: grafana
    restart: yes
    restart_policy: always
    image: grafana/grafana:9.5.3
    network_mode: net
    ports:
      - 3000:3000
    env: GF_SECURITY_ADMIN_PASSWORD={{ env.PASSWORD }}
      GF_SECURITY_ADMIN_USER={{ env.USER }}
      GF_FEATURE_TOGGLES_ENABLE=publicDashboards
      GF_LOG_LEVEL="debug"
      GF_SERVER_DOMAIN="notedwin.com"
      GF_SERVER_ROOT_URL="https://grafana.notedwin.com/"
    volumes:
      - /home/notedwin2/docker/grafana/:/etc/grafana/
