---

- name: Suppress login message
  file:
    path: "/home/notedwin/.hushlogin"
    mode: 0644
    owner: notedwin
    group: notedwin
    modification_time: preserve
    access_time: preserve
    state: touch

# - name: add tailscale
#   shell: curl -fsSL https://tailscale.com/install.sh | sh
#   args:
#     creates: /usr/local/bin/tailscale

- name: Update and Upgrade
  apt:
    upgrade: dist
    update_cache: yes

- name: Install system packages
  apt:
    name:
      - python3
      - git
      - neovim
      - tmux
      - curl
      - ca-certificates 
      - gnupg
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present

- name: Enable Docker remote access
  lineinfile:
    path: /lib/systemd/system/docker.service
    regexp: '^ExecStart='
    line: 'ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock'
    backup: yes


- name: Enabled passwordless sudo for {{item}}
  lineinfile:
    dest: /etc/sudoers
    regexp: "^wheel"
    line: '{{item }} ALL=(ALL) NOPASSWD:ALL'
    state: present
    validate: 'visudo -cf %s'
  loop: 
    - ansible
    - notedwin
    - docker

- name: Create Docker network
  docker_network:
    name: net
    driver: bridge
    state: present
    
- name: Restart Docker
  service:
    name: docker
    state: restarted