---
- name: Run a node exporter docker container
  docker_container:
    name: node_exporter
    image: prom/node-exporter
    state: started
    restart_policy: unless-stopped
    network_mode: net
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: --path.procfs /host/proc --path.sysfs /host/sys --path.rootfs /rootfs --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"

- name: Run motioneye
  docker_container:
    name: motioneye
    image: ccrisan/motioneye:master-amd64
    state: started
    restart_policy: unless-stopped
    network_mode: net
    ports:
      - "8765:8765"
    volumes: /home/notedwin/motioneye:/etc/motioneye
      /home/notedwin/motioneye:/var/lib/motioneye
      /etc/localtime:/etc/localtime:ro

- name: Run watchtowrr container
  docker_container:
    restart: yes
    name: watchtower
    image: containrrr/watchtower
    state: started
    restart_policy: unless-stopped
    network_mode: net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

- name: Run Portainer container
  docker_container:
    name: portainer
    image: portainer/portainer
    restart_policy: unless-stopped
    state: started
    network_mode: net
    ports:
      - 9000:9000
    env:
      AGENT_CLUSTER_ADDR: tasks.agent
      PORTAINER_DATA: /data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /home/notedwin2/docker/portainer:/data

- name: Run Homeassistant container
  docker_container:
    name: homeassistant
    image: homeassistant/home-assistant
    state: started
    restart_policy: unless-stopped
    network_mode: net
    ports:
      - "8123:8123"
    volumes:
      - /home/notedwin2/docker/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    env: TZ=America/Chicago
      PUID=1000
      PGID=100
