---
- name: copy ntfy.conf
  copy:
    src: ./configs/ntfy.yml
    dest: /home/notedwin2/docker/ntfy/server.yml
    owner: notedwin2
    group: notedwin2
    mode: 0644

- name: Run ntfy.com
  docker_container:
    name: ntfy
    image: binwiederhier/ntfy
    state: started
    network_mode: net
    restart_policy: unless-stopped
    command:
      - serve
    ports:
      - "82:80"
    volumes:
      - /home/notedwin2/docker/ntfy/server.yml:/etc/ntfy/server.yml
