---
- name: Copy Prometheus config file
  copy:
    src: ./configs/prometheus.yml
    dest: /home/notedwin2/docker/prometheus/prometheus.yml
    owner: notedwin2
    group: notedwin2
    mode: 0644
    force: yes

- name: Run Prometheus docker container
  docker_container:
    name: prometheus
    image: prom/prometheus
    user: root
    state: started
    restart_policy: unless-stopped
    network_mode: net
    ports:
      - "9090:9090"
    volumes:
      - /home/notedwin2/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/notedwin2/docker/prometheus/data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
