global:
  # How frequently to scrape targets by default.
  scrape_interval: 30s

scrape_configs:
  - job_name: caddy
    static_configs:
    # TODO: HARDCODED IP
      - targets: ['192.168.0.109:2019']

  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node_exporter:9100"]

  - job_name: rsp
    static_configs:
      - targets: ['192.168.0.102:9100']