title: notedwin -- Home
cardBlur: sm
# theme: dark
# color: slate

layout:
  Media:
    style: row
    columns: 4

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

hideVersion: true
showStats: true
