---
- name: Deploy services on linux server
  hosts: server
  gather_facts: false
  become: yes
  tasks:

    - name: Get env file content
      include_vars:
        file: env.yml
        name: env
      
    - name: Run Grafana container
      docker_container:
        name: grafana
        restart: yes
        restart_policy: always
        image: grafana/grafana:9.5.3
        network_mode: my_network
        ports:
          - 3000:3000
        env: 
          GF_SECURITY_ADMIN_PASSWORD={{ env.PASSWORD }}
          GF_SECURITY_ADMIN_USER={{ env.USER }}
          GF_FEATURE_TOGGLES_ENABLE=publicDashboards
          GF_SERVER_SERVER_FROM_SUB_PATH="FALSE"
          GF_LOG_LEVEL="debug"
          GF_SERVER_DOMAIN="notedwin.com"
          # GF_SERVER_ROOT_URL="https://grafana.notedwin.com/"
        volumes:
          # move this to home notedwin
          - grafana:/var/lib/grafana