---
- name: Deploy services on linux server
  hosts: server
  gather_facts: false
  become: yes
  tasks:

    - name: Get env file content
      include_vars:
        file: env.yml
        name: env
      
    - name: Run Transmission docker container
      docker_container:
        restart: yes
        name: transmission
        image: lscr.io/linuxserver/transmission:latest
        state: started
        restart_policy: unless-stopped
        network_mode: my_network
        ports:
          - "9091:9091"
          - "51413:51413"
          - "51413:51413/udp"
        volumes:
          - /home/notedwin/Downloads:/downloads
        env:
          PUID=1000
          PGID=1000
          TZ=America/Chicago