---
- name: Deploy
  hosts: test
  gather_facts: false
  become: yes
  tasks:
    - name: Get env file content
      include_vars:
        file: env.yml
        name: env

    - name: Run Linux setup task
      import_tasks: tasks/linux.yml

    - name: Run Caddy setup task
      import_tasks: tasks/caddy.yml
    
    - name: Run Misc setup task
      import_tasks: tasks/misc.yml