---
- name: Deploy
  hosts: test
  gather_facts: false
  become: yes
  tasks:
    - name: Get env file content
      include_vars:
        file: env.yml
        name: env

    - name: adguard
      import_tasks: tasks/adguard.yml

    # - name: Homepage
    #   import_tasks: tasks/homepage.yml
    # ... other tasks, try to keep empty when pushing to git
