---
- name: Setup homelab main
  hosts: spark
  gather_facts: true
  become: true
  module_defaults:
    docker_container:
      state: started
      network_mode: net
      restart_policy: unless-stopped
      restart: true
    file:
      owner: notedwin
      group: notedwin
      mode: "0775"
    template:
      owner: notedwin
      group: notedwin
      mode: "0775"
    copy:
      owner: notedwin
      group: notedwin
      mode: "0775"

  tasks:
    - name: Get env file content
      include_vars:
        file: env.yml
        name: env

    - name: Install things
      ansible.builtin.include_tasks: "{{ item }}/{{ item }}.yml"
      loop:
        - homepage
