---
- name: Deploy services on linux server
  hosts: server
  gather_facts: false
  become: yes
  tasks:

    - name: Get env file content
      include_vars:
        file: env.yml
        name: env
      
    - name: Run watchtowrr container
      docker_container:
        restart: yes
        name: watchtower
        image: containrrr/watchtower
        state: started
        restart_policy: unless-stopped
        network_mode: my_network
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock