---
- name: Deploy Caddy
  hosts: server
  gather_facts: false
  become: yes
  tasks:
    - name: Get env file content
      include_vars:
        file: env.yml
        name: env
       
    - name: Copy Caddyfile
      copy:
        src: ./configs/caddyfile
        dest: /home/notedwin/Caddyfile
        owner: root
        group: root
        mode: 0644
        force: yes
    
    - name: Copy caddy dockerfile
      copy:
        src: ./configs/dockerfile
        dest: /home/notedwin/caddy/Dockerfile
        owner: notedwin
        group: notedwin
        mode: 0644
        force: yes
    
    - name: Build Docker image for Caddy if not exists
      docker_image:
        name: caddy-yuh
        source: build
        build:
          path: /home/notedwin

      # become_user: notedwin
      # command: docker build -t caddy-yuh /home/notedwin

    - name: Run Caddy docker container
      docker_container:
        restart: yes
        user: root
        name: caddy
        # hostname: notedwin
        image: caddy-yuh
        state: started
        restart_policy: always
        network_mode: my_network
        ports:
          - "80:80"
          - "443:443"
          - "2019:2019"
        volumes:
          - /home/notedwin/Caddyfile:/etc/caddy/Caddyfile
          - /home/notedwin/caddy:/data
          - /home/notedwin/caddy:/config
          - /var/log/caddy/:/var/log/caddy/
          - /home/notedwin/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
          - /resume/resume.pdf:/resume/resume.pdf