---
- name: Deploy services on linux server
  hosts: server
  gather_facts: false
  become: yes
  tasks:

    - name: Get env file content
      include_vars:
        file: env.yml
        name: env
      
    - name: Run tailscale container
      docker_container:
        restart: yes
        name: tailscale
        image: tailscale/tailscale
        state: started
        restart_policy: unless-stopped
        network_mode: host
        # add net_admin capability to the container
        capabilities:
          - net_admin
          - net_raw
        volumes:
          - /dev/net/tun:/dev/net/tun
          - /home/notedwin/tailscale/varlib:/var/lib
          # https://github.com/tailscale/tailscale/issues/6849
          # add volume for the tailscaled.sock to be present on the host system
          # that's where caddy goes to communicate with tailscale
          - /home/notedwin/tailscale:/tmp
        env:
        # LOL I accidently commited this, but its fine because its a single use key:>
          TS_AUTHKEY: tskey-auth-kyBPCa2CNTRL-9L2J4nyTSMRvzE82m3zMMRCkgxF5FFjQ
          TS_STATE_DIR: /var/lib/tailscale
        # create a cert using docker exec
        # docker exec tailscaled tailscale --socket /tmp/tailscaled.sock cert <the server domain name>
        # then copy the cert to the host system

    # - name: Create tailscale cert
    #   shell: docker exec tailscale tailscale --socket /tmp/tailscaled.sock cert notedwin.cow-ghost.ts.net
    #   args:
    #     executable: /bin/bash