---
- name: create data dir for grafana
  file:
    path: "/home/{{env.USER}}/docker/grafana/{{ item }}"
    state: directory
  loop:
    - data
    - config

- name: Copy grafana folder
  copy:
    src: grafana/
    dest: "/home/{{env.USER}}/docker/grafana/config"
    force: yes

- name: copy templated datasources
  template:
    src: all.j2
    dest: "/home/{{env.USER}}/docker/grafana/config/provisioning/datasources/all.yml"

- name: copy templated ini
  template:
    src: grafana.j2
    dest: "/home/{{env.USER}}/docker/grafana/config/grafana.ini"

- name: Run Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    user: "1000:1000"
    ports:
      - 3000:3000
    volumes:
      - /home/{{env.USER}}/docker/grafana/config:/etc/grafana/
      - /home/{{env.USER}}/docker/grafana/data:/var/lib/grafana/
