---
- name: copy templated prometheus config
  template:
    src: prometheus.j2
    dest: "/home/{{env.USER}}/docker/prometheus/prometheus.yml"

- name: Run Prometheus docker container
  docker_container:
    name: prometheus
    user: root
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/{{env.USER}}/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/{{env.USER}}/docker/prometheus/data:/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles

- name: Run a node exporter docker container
  docker_container:
    name: node_exporter
    user: root
    image: prom/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: --path.procfs /host/proc --path.sysfs /host/sys --path.rootfs /rootfs --collector.filesystem.ignored-mount-points "^/(sys|proc|dev|host|etc)($$|/)"
